FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt ./
COPY main.py ./
COPY /data/database.db ./data/
COPY /static/css/style.css ./static/css/
COPY /static/js/chat.js ./static/js/
COPY /templates/index.html ./templates/
COPY LICENSE.md ./
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 80
CMD ["python", "main.py"]
